config/routes.rb
Sound::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :playlists do
    collection do
      get 'add_song'
    end
  end

  resources :songs do
    collection do
      post 'upload'
      get 'comments'
    end
  end

  resources :relationships, only: [:create, :destroy]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: 'home#index'
  mount Resque::Server, :at => "/resque"

end

app/models/user.rb
class User < ActiveRecord::Base
  include AASM

  # attr_accessible :provider, :uid, :name, :first_name, :last_name, :oauth_token,
                  # :oauth_expires_at, :city, :country, :description, :photo

  has_many :songs
  has_many :playlists, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  has_attached_file :photo,
                    styles: {
                    thumb: '150x150>',
                    medium: '300x300>'
                    }

  validates_attachment_content_type :photo,
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  aasm do
    state :greenman, initial: true
    state :guruman
    state :meloman

    event :guru do
      transitions :from => :greenman, :to => :guruman
    end
    event :melo do
      transitions :from => :guruman, :to => :meloman
    end
    event :green do
      transitions :from => [:guruman, :greenman], :to => :greenman
    end
  end

  def user_status
    quantity = followers.count
    if quantity.between?(20, 49)
      guru!
    elsif quantity >= 50
      melo!
    else
      green!
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.photo = process_uri(auth.info.image)
      user.save!
    end
  end

  def following?(other_user)
    relationships.where(followed_id: other_user.id).first
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.where(followed_id: other_user.id).first.destroy
  end

private

  def self.process_uri(uri)
    return if uri.blank?
    avatar_url = URI.parse(uri)
    avatar_url.scheme = 'https'
    avatar_url.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user, except: [:index]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @playlists = Playlist.paginate(page: params[:page])
    @users = User.all
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = I18n.t 'controllers.users.updated'
      redirect_to user_path
    else
      flash[:alert] = I18n.t 'controllers.users.not_updated'
      render :edit
    end
  end

  def following
    @users = @user.followed_users
  end

  def followers
    @users = @user.followers
  end

private

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/users/_follow.html.haml
= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f|
  = f.hidden_field :followed_id
  = f.submit I18n.t 'views.users.follow'

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_form.html.haml
= form_for @user do |f|
  %br/
  = f.file_field :photo
  %br/
  = f.label I18n.t 'views.users.name'
  %br/
  = f.text_field :name
  %br/
  = f.label I18n.t 'views.users.first_name'
  %br/
  = f.text_field :first_name
  %br/
  = f.label I18n.t 'views.users.last_name'
  %br/
  = f.text_field :last_name
  %br/
  = f.label I18n.t 'views.users.city'
  %br/
  = f.text_field :city
  %br/
  = f.label I18n.t 'views.users.country'
  %br/
  = f.text_field :country
  %br/
  = f.label I18n.t 'views.users.description'
  %br/
  = f.text_field :description
  %br/
  %br/
  = f.submit I18n.t 'views.users.update'

app/views/users/_show_follow.html.haml
- if @users.any?
  = render @users

app/views/users/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => following_user_path(@user)}
    %strong#following.stat
      = @user.followed_users.count
    = I18n.t 'views.users.following'
  %a{:href => followers_user_path(@user)}
    %strong#followers.stat
      = @user.followers.count
    = I18n.t 'views.users.followers'

app/views/users/_unfollow.html.haml
= form_for(current_user.relationships.where(followed_id: @user).first, html: { method: :delete }, remote: true) do |f|
  = f.submit I18n.t 'views.users.unfollow'

app/views/users/_user.html.haml
%li
  = link_to user.name, user

app/views/users/_users_folowers.html.haml
%section
  %h1= @user.name
  %span= link_to I18n.t 'views.users.view_profile', @user
%section
  = render 'users/stats'

app/views/users/edit.html.haml
.container{:style => "background-color: #e9e9e9; min-height: 80%;"}
  .center_block
    = render 'form'

app/views/users/followers.html.haml
.container{:style => "background-color: #e9e9e9; min-height: 80%;"}
  .center_block
    = render 'users_folowers'
    %h3= I18n.t 'views.users.followers'
    = render 'show_follow'

app/views/users/following.html.haml
.container{:style => "background-color: #e9e9e9; min-height: 80%;"}
  .center_block
    = render 'users_folowers'
    %h3= I18n.t 'views.users.following'
    = render 'show_follow'

app/views/users/index.html.haml
.container{:style => "background-color: #e9e9e9; min-height: 80%;"}
  .center_block
    %h2= I18n.t 'views.users.list'
    = will_paginate @users, :style => 'color:black'
    %table{:cellspacing => '0', :width => '80%'}
      %thead
      %tbody
        - @users.each do |user|
          %tr
            %td
              = image_tag user.photo.url(:thumb)
            %td
              %h4= link_to user.name, user_path(user)
              %h4.orange= user.aasm_state
              - user ||= current_user
              .stats
                %a{:href => following_user_path(user)}
                  %strong#following.stat
                    = user.followed_users.count
                  = I18n.t 'views.users.following'
                %a{:href => followers_user_path(user)}
                  %strong#followers.stat
                    = user.followers.count
                  = I18n.t 'views.users.followers'
              %br/

  = will_paginate @users, :style => 'color:black'

app/views/users/show.html.haml
.container{:style => "background-color: #e9e9e9; min-height: 80%;"}
  .center_block
    .row
      .col-xs-9.col-md-6
        %br/
        = image_tag @user.photo.url(:medium)
        %br/
        %h3= @user.name
        - if signed_in?
          %h4.orange= @user.aasm_state
          = render 'follow_form'
          %br/
          = render 'stats'
          %br/
        - if @user == current_user
          %a.btn.btn-default{:href => edit_user_path(@user)}
            %span.glyphicon.glyphicon-pencil>
            = I18n.t('views.users.edit')
          %br/
          %br/

      .col-xs-9.col-md-6
        %br/
        - @playlists.each do |playlist|
          - if current_user?(playlist.user)
            - playlist.songs.each_with_index do |song, i|
              = render 'shared/player', :song_for_player => song
        %br/
        = render 'songs/upload'
        %h5= link_to 'New playlist',new_playlist_path

app/views/users/show_follow.html.haml
%section
  %h1= @user.name
  %span= link_to "view profile", @user
%section
  = render 'users/stats'
%h3= @title
- if @users.any?
  = render @users