config/routes.rb
Sound::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :playlists do
    collection do
      get 'add_song'
    end
  end

  resources :songs do
    collection do
      post 'upload'
      get 'comments'
    end
  end

  resources :relationships, only: [:create, :destroy]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: 'home#index'
  mount Resque::Server, :at => "/resque"

end

app/models/song.rb
class Song < ActiveRecord::Base
  require "id3tag"

  after_commit :set_song_attr_from_id3tag, :on => :create

  # attr_accessible :artist, :title, :year, :mfile, :album, :track_nr, :genre, :user_id

  belongs_to :user
  has_and_belongs_to_many :playlists
  has_attached_file :mfile

  validates :user, presence: true, :on => :update
  validates_attachment :mfile,
      :presence => true,
      :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] },
      :file_name => { :matches => [/mp3\Z/] },
      :size => { :in => 0..15.megabytes }

  def set_song_attr_from_id3tag
    song = ID3Tag.read(File.open("#{Rails.root}/public" + self.mfile.url))
    self.attributes.each_key do |attr|
      next unless song.respond_to? attr
      self[attr] ||= song.send(attr.to_sym)
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  include MailSendingLogic

  before_filter :find_song, :only => [:edit, :update, :destroy, :comments]

  def index
    @songs = Song.search params[:search], :page => params[:page], :per_page => 30
  end

  def upload
    @song = Song.create(song_params)
    @song.user_id = current_user.id
    if @song.save
      user_ids = current_user.followers.map(&:id)
      Resque.enqueue(NotifyMailer, user_ids, @song.id)
      Resque.enqueue(Reindexing)
      render :action => 'edit'
    else
      flash[:alert] = I18n.t 'controllers.songs.not_uploaded'
    end
  end

  def edit
  end

  def update
    @song.update_attributes!(song_params) if @song.changed?
    flash[:notice] = I18n.t 'controllers.songs.uploaded'
    redirect_to(:controller => 'songs', :action => 'index')
  rescue
    flash[:alert] = I18n.t 'controllers.songs.not_uploaded'
    render 'users/show'
  end

  def destroy
    if @song
      @song.destroy
      flash[:notice] = I18n.t 'controllers.songs.destroyed'
    else
      flash[:alert] = I18n.t 'controllers.songs.not_destroyed'
    end
    redirect_to(:controller => 'songs', :action => 'index')
  end

  def comments
  end

  private

  def find_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :artist, :year, :mfile_file_name, :mfile_content_type, :mfile_file_size, :mfile_updated_at, :album, :track_nr, :genre)
  end
end

app/views/songs/_form.html.haml
%h1= I18n.t 'views.songs.upload_new_MP3'
= form_for @song do |f|
  = f.label I18n.t 'views.songs.title'
  %br/
  = f.text_field :title
  %br/
  = f.label I18n.t 'views.songs.artist'
  %br/
  = f.text_field :artist
  %br/
  = f.label I18n.t 'views.songs.year'
  %br/
  = f.text_field :year
  %br/
  = f.label I18n.t 'views.songs.genre'
  %br/
  = f.text_field :genre
  %br/
  = f.label I18n.t 'views.songs.album'
  %br/
  = f.text_field :album
  %br/
  = f.label I18n.t 'views.songs.track_nr'
  %br/
  = f.text_field :track_nr
  %br/
  %br/

  = f.submit I18n.t 'views.songs.upload'

app/views/songs/_upload.html.haml
= form_for Song.new, url: upload_songs_path do |f|
  = f.file_field "mfile"
  %br/

app/views/songs/comments.html.haml
.center_block
  %h3= I18n.t "views.songs.title"
  = @song.title
  %h3= I18n.t "views.songs.artist"
  = @song.artist
  %br/
  %br/
  = render 'shared/player', :song_for_player => @song
  #disqus
    #disqus_thread

app/views/songs/edit.html.haml
.container{:style => "background-color: #e9e9e9; min-height: 80%;"}
  .center_block
    = render 'form'

app/views/songs/index.html.haml
.container{:style => "background-color: #e9e9e9; min-height: 80%;"}
  .center_block
    %h2= I18n.t 'views.songs.list'
    = will_paginate @songs, :style => 'color:black'
    %table{:cellspacing => '0', :width => '100%'}
      %thead
      %tbody
        - @songs.each_with_index do |song, i|
          %tr
            %td
              = image_tag("logo5.jpg", height: "80", width: "80", class: "img-circle")
            %td= render 'shared/player', :song_for_player => song
            %td
              %a.btn.btn-default{:href => playlists_path(:song_id => song)}
                %span.glyphicon.glyphicon-plus
            %td
              %a.btn.btn-default{:href => comments_songs_path(:id => song)}
                %span.glyphicon.glyphicon-check
                = I18n.t 'views.songs.comments'
            %td
              %br/
  = will_paginate @songs, :style => 'color:black'