config/routes.rb
Sound::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :playlists do
    collection do
      get 'add_song'
    end
  end

  resources :songs do
    collection do
      post 'upload'
      get 'comments'
    end
  end

  resources :relationships, only: [:create, :destroy]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: 'home#index'
  mount Resque::Server, :at => "/resque"

end

app/views/layouts/_footer.html.erb
<div class="container marketing">
    <div class="row">
      <div class="col-xs-6 col-sm-4">
        <%= image_tag("logo5.jpg", height: "140", width: "140", class: "img-circle") %>
        <h2>Songs</h2>
        <p>Upload your favorite music and enjoy it! Don't forget to share it with friends!</p>
        <p><a class="btn btn-default" href="<%= songs_path %>" role="button">List songs &raquo;</a></p>
      </div>
      <div class="col-xs-6 col-sm-4">
        <%= image_tag("logo1.jpg", height: "140", width: "140", class: "img-circle") %>
        <h2>Playlists</h2>
        <p>Simply, the list of your adorable music! Don't forget to create one!</p>
        <p><a class="btn btn-default" href="<%= playlists_path %>"  role="button">List playlists &raquo;</a></p>
      </div>
      <div class="col-xs-6 col-sm-4">
        <%= image_tag("logo3.jpg", height: "140", width: "140", class: "img-circle") %>
        <h2>Meloman</h2>
        <p>Person who really understands music life! Don't forget to find one and follow!</p>
        <p><a class="btn btn-default" href="<%= users_path %>"  role="button">List users &raquo;</a></p>
      </div>
    </div>
    <footer>
      <p class="pull-right"></p>
      <p>&copy; 2015 MusicLoud</p>
    </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="row">
    <div class="col-xs-6 col-md-4"><div class="left-side"><%= link_to "musicloud", root_path, id: "logo" %></div></div>
    <div class="col-xs-6 col-sm-4 header_up ">
      <% if current_user %>
        <%= render 'shared/search', :path => songs_path %></div>
      <div class="col-xs-6 col-sm-4 header_up">
        <div style="color:#b7b7b7"><%= I18n.t("views.layouts.signed_in") %><strong><%= link_to current_user.name, current_user %> | </strong>
        <%= link_to I18n.t("views.layouts.sign_out"), signout_path, id: "sign_out" %></div>
      <% else %>
        <div id="right">
          <%= link_to I18n.t("views.layouts.sign_in") , "/auth/facebook", id: "sign_in" %></div></div>
      <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soundcloud</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render 'layouts/header'%>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
      <%= yield %>
    <%= render 'layouts/footer'%>
  </div>
</body>
</html>